site_name: Kasper's AZ-400 notes
site_author: Kasper Kornak
repo_name: KasperKornak/AZ-400-learning
docs_dir: MicrosoftLearningPath
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky