site_name: Kasper's AZ-400 notes
site_author: Kasper Kornak
repo_name: KasperKornak/AZ-400-learning
docs_dir: MicrosoftLearningPath
theme:
  name: material
  language: en
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky

  palette:
  - scheme: default
    toggle:
      icon: material/brightness-4
      name: switch to light mode
  - scheme: slate
    toggle:
      icon: material/brightness-7
      name: switch to dark mode
    